name: Cpp CI

on:
  push:
    branches:
      - main
      - Implementation
      
jobs:
  build-and-sonar:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compile
        run: g++ Wordle.cpp -o app
